version: '3.8'

services:
  # Сервис PostgreSQL
  db:
    image: postgres:latest
    container_name: post-db
    environment:
      POSTGRES_DB: postdb
      POSTGRES_USER: postuser
      POSTGRES_PASSWORD: postpass
      PGDATA: /var/lib/postgresql/data/pgdata  # Улучшает персистентность
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postuser -d postdb"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Сервис приложения
  app:
    build: .
    container_name: blog-app
    ports:
      - "8081:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/postdb
      SPRING_DATASOURCE_USERNAME: postuser
      SPRING_DATASOURCE_PASSWORD: postpass
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver
    depends_on:
      - db
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/api/posts?search=&pageNumber=1&pageSize=1"]
      interval: 30s
      timeout: 10s
      retries: 3

# Объём для данных PostgreSQL
volumes:
  postgres-data:
    driver: local
